// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3U5IB5Gy2iz8JnDdZjKtUhM8vEncG728',
    appId: '1:133788893267:web:3d83d7c64a43382b0b06a6',
    messagingSenderId: '133788893267',
    projectId: 'paysync-329b1',
    authDomain: 'paysync-329b1.firebaseapp.com',
    storageBucket: 'paysync-329b1.firebasestorage.app',
    measurementId: 'G-E5MNQSB9B9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDBsiNBZATxIBkfipLQZ3v02Lzy9lhQP8',
    appId: '1:373674165454:android:6c4583049f7d69ed61fc9f',
    messagingSenderId: '373674165454',
    projectId: 'paysync-58239',
    storageBucket: 'paysync-58239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7-A6irVUgo9bRrUxg6-wVy8NsxAbiPaU',
    appId: '1:373674165454:ios:5e14afa555a98c3361fc9f',
    messagingSenderId: '373674165454',
    projectId: 'paysync-58239',
    storageBucket: 'paysync-58239.firebasestorage.app',
    iosBundleId: 'com.example.paysync',
  );

}